matrix:
    include:
        - os: osx
          language: objective-c
          python:
            - "3.6"
          sudo: required
          env:
            - TOXENV=py36
          install:
            - "PYTHONPATH=. pyinstaller --onefile pyportify.spec"
            - "hdiutil create dist/pyportify.dmg -srcfolder dist/ -ov"
          deploy:
            - provider: releases
              api_key:
                secure: SXoKAyll1TtFrQeOS5i65tzZLdZlXx5jEOnL3tlblmgcEn0sD4iILV/K/qv8KmeE8biBIdbtcqNJPh65covL8Yidaz211Hc4/MHhBU+rfqnrN0EcPR53/zmUgSbzWl7p62zvHdMSmS/iKQKT6Kv3pvyTEDL35oVX8lx0ckzcjkY
              skip_cleanup: true
              file: 'dist/pyportify.dmg'
              on:
                all_branches: true
                repo: rckclmbr/pyportify
                tags: true
            - provider: pypi
              user: jbraegger
              password:
                secure: P3dSxH4hgJ6JdnGc4zcCneM/jn2qczOh11uxFSJGHEvkMvL4vOrZ0yOiE8BBInUBeT/4kVfWNuBghibS1P06AlWWvUz66KHc719mpHBA3On+q/0troVXT1Pl9xiEr8ITvQda7wWgSZaxSVpaZnkMJZQQkR3ucc7p6qm4mygPyjs=
              on:
                all_branches: true
                repo: rckclmbr/pyportify
                tags: true
        - os: linux
          python: "3.6"
          env:
            - TOXENV=py36
          language: python
          sudo: required
          before_install:
            - "sudo apt-get update"
            - "sudo apt-get install python-all-dev"
            - "pip3 install tox"
before_install:

  # Install python 3.6.3 on OS X
  # Workaround for Travis's current lack of official support for Python on OS X
  # Reference https://github.com/travis-ci/travis-ci/issues/2312
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      echo "TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION";

      echo Updating Homebrew...;
      brew update;

      echo Installing pyenv...;
      brew unlink pyenv;
      brew install pyenv;

      echo Installing pyenv shims...;
      eval "$(pyenv init -)"

      new_python_version="3.6.3";

      echo "Installing Python${new_python_version}...";
      env PYTHON_CONFIGURE_OPTS="--enable-framework" pyenv install ${new_python_version};
      pyenv versions;

      echo "Making Python${new_python_version} the global python...";
      pyenv global ${new_python_version};

      echo "python --version" `python --version`;
      echo "pip --version" `pip --version`;

      echo Upgrading pip...;
      pip install --upgrade pip;

      echo Installing package dependencies...;
      pip3 install pyinstaller==3.3 tox;
      pip3 install -r requirements.txt;
      pandoc -f markdown -t rst -o README.rst README.md;
    fi

script: tox
